### ISSUE TITLE
[BUG] Not a valid go stack

### ISSUE THREAD

**Issue by sspaink** [A-0-5/gostmortem-table#11]
### Version

v0.0.1 

### Category

Functionality

### Issue Description

Receiving the error "Not a valid go stack" when trying to visualize what I think is a valid go stack trace.

I can reproduce it with the following simple program:

```go
package main

func main() {
	panic("lol")
}
```

Then trying to visualize the resulting stack trace, the extension fails with "Not a valid go stack"

```
panic: lol

goroutine 1 [running]:
main.main()
        /Users/sspaink/Sandbox/testpanic/main.go:4 +0x2c
exit status 2
```

Not sure what is wrong with this stack trace, is there more error information somewhere? Thanks for taking a look. This extension idea is pretty neat!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by A-0-5** [comment]
Hi @sspaink , I believe there are 2 issues here 
1. The parser in this extension is configured to handle primarily the stack trace only. The panic builtin method adds the additional lines `panic: <message>` and `exit status <exit code>`
```diff
-panic: lol
-
+goroutine 1 [running]:
+main.main()
+        /Users/sspaink/Sandbox/testpanic/main.go:4 +0x2c
-exit status 2
```
The lines in green are the actual stack trace and only that is what the parser would be able to comprehend. This was not covered because my original use case for building this was to read panics in logs that are generated  by recovery methods and the stack is usually logged separately by getting using `debug.stack()` or `runtime.stack()` in its own logline or json object in case of structured logging.

2. The second issue I could see was the actual stack trace that you provided seems to be indenting frames with spaces instead of tabs. Which is usually not the case as the standard indentation for goroutine stack traces is tabs. I am  not sure if this is an editor setting that is causing this but its fairly straight forward to convert indentations to tabs using 
- paste only the lines highlighted in green (stack only)
- cmd/ctrl + shift + p
- type `Convert Indentation to Tabs`
- then run the extension and it should work fine. 

Currently I am a bit occupied with my regular work , I will take this up as a feature improvement to support this usecase as well
Do let me know if this worked for you

**Comment by sspaink** [comment]
Thank you for the detailed response! Removing the extra lines and using tabs instead solved the problem and it now works as expected.

**Comment by A-0-5** [comment]
Awesome I'll close this issue and take the new feature up when I find some time
