### ISSUE TITLE
Typo in banner

### ISSUE THREAD

**Issue by ChristoWolf** [A-0-5/gostmortem-table#2]
Hi!

The tool's name in the banner has a typo: gostmor**e**tem

**Comment by A-0-5** [comment]
Thank you for reporting this.
This has now been fixed in [270767f](https://github.com/A-0-5/gostmortem-table/commit/270767f9034ee62de3a57c383b0d26e5a74b2a17). 
[Marketplace Listing](https://marketplace.visualstudio.com/items?itemName=AOS.gostmortem-table) is also updated as it picks up the banner from the repo directly.
